services:
  postgres-db:
    image: postgres:16
    container_name: postgres-db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init/db/:/docker-entrypoint-initdb.d/:ro
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: trail-race

  rabbitmq:
    image: rabbitmq:4-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"  # RabbitMQ management console
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin

  race_application_query_service:
    build:
      context: ./race_application_query_service
      dockerfile: Dockerfile
    environment:
      DB_HOST: postgres-db
      DB_PORT: 5432
      DB_NAME: trail-race
      DB_USERNAME: admin
      DB_PASSWORD: admin
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: admin
      SPRING_RABBITMQ_PASSWORD: admin
      SPRING_PROFILES_ACTIVE: docker
      CORS_ALLOWED_ORIGIN: http://localhost:3000
    depends_on:
      - postgres-db
      - rabbitmq
    ports:
      - "8081:8080"

  race_application_command_service:
    build:
      context: ./race_application_command_service
      dockerfile: Dockerfile
    environment:
      DB_HOST: postgres-db
      DB_PORT: 5432
      DB_NAME: trail-race
      DB_USERNAME: admin
      DB_PASSWORD: admin
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: admin
      SPRING_RABBITMQ_PASSWORD: admin
      SPRING_PROFILES_ACTIVE: docker
      CORS_ALLOWED_ORIGIN: http://localhost:3000
    depends_on:
      - postgres-db
      - rabbitmq
    ports:
      - "8082:8080"

volumes:
  postgres_data:
  rabbitmq_data: