spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/trail-race
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin
    queues:
      race: race.events
      application: application.events
    exchanges:
      race: race.events.exchange
      application: application.events.exchange
    routing-keys:
      race: race.events.#
      application: application.events.#

logging:
  level:
    root: INFO
    com.intellexi.race_app_qs: DEBUG

server:
  port: 8081

security:
  jwt:
    secret: "JEAitoIlupFy7I1t3xIGlUQARV3rtpdYCfLwCrNJVcCYv9tZfRuz/FtsB+DvE9DQ"

cors:
  allowed-origin: http://localhost:3000