spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/trail-race
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin

logging:
  level:
    root: INFO
    com.intellexi.race_app_cs: DEBUG

server:
  port: 8082

security:
  jwt:
    secret: "JEAitoIlupFy7I1t3xIGlUQARV3rtpdYCfLwCrNJVcCYv9tZfRuz/FtsB+DvE9DQ"

cors:
  allowed-origin: http://localhost:3000
